[package]
name = "phil_starknet_integration"
version = "0.1.0"
edition = "2024_07"
license = "MIT"

[lib]

[dependencies]
starknet = "2.15.0"
phil_cairo_air_adapter_spike = { path = "../cairo_air_adapter_spike" }

[dev-dependencies]
cairo_test = "2.15.0"

[cairo]
enable-gas = true

[[target.starknet-contract]]
casm = true
allowed-libfuncs-list.name = "experimental"
