import CryptoKit
import Foundation

/// Independent Swift reconstruction of the Step 6C request graph. No supplied
/// derived hash becomes authority until it is reproduced from raw records.
enum RoutineAuthorizationCanonicalVerifier {
    struct Verified {
        let requestId: Data, sessionId: Data, expiresAt: UInt64, signingDigest: Data
        let deviceId: String, deviceKeyId: String, presentationHash: String, approvalDigest: String
        let responseFormatVersionHash: String, deviceEpoch: String
        let presentation: RoutineAuthorizationPresentation
    }

    private static let zero = "0x" + String(repeating: "00", count: 32)
    private static let labels = ["Phil Step 6C Local Harmless App", "Local Hardhat Chain 31337", "Disposable Phil Routine Account", "Harmless Local Record Target", "Record Harmless Local Value", "Harmless Record Parameters"]
    private static let suite = domain("phil-signature-p256-sha256-prehash-raw-rs-low-s-v2")
    private static let provider = domain("apple-secure-enclave-p256-x962-sha256-digest-der-v1")
    private static let wire = domain("phil-p256-signature-rs-64-low-s-v1")
    private static let application = domain("phil-application-step6c-local-harmless-v1")
    private static let scope = domain("phil-scope-step6c-local-routine-v1")
    private static let adapter = domain("phil-adapter-step6c-local-erc4337-v07-v1")
    private static let network = domain("phil-local:step6c:31337")
    private static let actionType = domain("PHIL_EVM_SINGLE_CALL_V1")
    private static let recorded = domain("PHIL_STEP6C_HARMLESS_VALUE_V1")
    private static let selector = String(domain("record(bytes32,bool)").prefix(10))

    static func verify(_ root: [String: Any], bootstrap: RoutineAuthorizationBootstrap,
                       record: RoutineApprovalPublicRecord, fingerprint: String, now: UInt64) throws -> Verified {
        try exact(root, ["formatVersionHash","executionEnvironment","adapterManifest","signatureRegistry","deviceEnrollment","accountConfiguration","catalogEntries","capabilityPolicy","action","targetCalldata","authorizationEnvelope","unsignedDeviceApproval","humanPresentation","authorizationCore","executionEnvironmentHash","adapterManifestHash","signatureRegistryHash","deviceEnrollmentHash","accountConfigurationHash","catalogHash","capabilityPolicyHash","actionHash","authorizationEnvelopeDigest","humanPresentationHash","authorizationCoreDigest","approvalNonce","deviceApprovalDigest","requestId","platformSigningDigest"])
        try equal(try s(root,"formatVersionHash"), domain("PHIL_ROUTINE_AUTHORIZATION_REQUEST_V1"), field:"root.formatVersionHash")

        let env = try object(root,"executionEnvironment", ["formatVersionHash","environmentClass","chainId","networkIdHash","executionEnvironmentId","adapterId","entryPointVersionHash","entryPoint","entryPointRuntimeCodeHash","senderCreator","senderCreatorRuntimeCodeHash","externalNetwork","productionAuthority","meaningfulAssets","executionEnvironmentHash"])
        try equal(try s(env,"formatVersionHash"),domain("PHIL_EXECUTION_ENVIRONMENT_V1"), field:"env.formatVersionHash"); try equal(try n(env,"environmentClass"),1, field:"env.environmentClass")
        try equal(try s(env,"chainId"),"31337", field:"env.chainId"); try equal(try s(env,"networkIdHash"),network, field:"env.networkIdHash")
        try equal(try s(env,"executionEnvironmentId"),domain("phil-execution-environment-step6c-local-hardhat-v1"), field:"env.executionEnvironmentId"); try equal(try s(env,"adapterId"),adapter, field:"env.adapterId")
        try equal(try s(env,"entryPointVersionHash"),domain("erc4337-entrypoint-v0.7.0"), field:"env.entryPointVersionHash"); try requireFalse(env,["externalNetwork","productionAuthority","meaningfulAssets"])
        let entryPoint = try address(env,"entryPoint"), senderCreator = try address(env,"senderCreator")
        let environmentHash = hash([b(domain("PHIL_EXECUTION_ENVIRONMENT_V1")),u("1"),u("31337"),b(network),b(domain("phil-execution-environment-step6c-local-hardhat-v1")),b(adapter),b(domain("erc4337-entrypoint-v0.7.0")),a(entryPoint),try bw(env,"entryPointRuntimeCodeHash"),a(senderCreator),try bw(env,"senderCreatorRuntimeCodeHash"),u("0"),u("0"),u("0")])
        try equal(try s(env,"executionEnvironmentHash"),environmentHash, field:"env.executionEnvironmentHash"); try equal(try s(root,"executionEnvironmentHash"),environmentHash, field:"root.executionEnvironmentHash")

        let manifest = try object(root,"adapterManifest", ["adapterId","adapterVersionHash","adapterType","networkIdHash","accountModelId","scopeCanonicalizationId","actionCodecId","replayModelId","feeModelId","supportedDeviceSignatureSuiteIds","supportedProofSuiteIds","postQuantumCapability","implementationHash","auditStatusHash","manifestHash"])
        try equal(try s(manifest,"adapterId"),adapter, field:"manifest.adapterId"); try equal(try s(manifest,"adapterVersionHash"),domain("phil-step6c-local-erc4337-adapter-v1"), field:"manifest.adapterVersionHash"); try equal(try n(manifest,"adapterType"),1, field:"manifest.adapterType"); try equal(try s(manifest,"networkIdHash"),network, field:"manifest.networkIdHash")
        let accountModel=domain("phil-evm-erc4337-narrow-account-binding-v1"), scopeCanon=domain("phil-scope-eip155-chain-account-v1"), codec=domain("phil-evm-single-call-hash-codec-v1"), replay=domain("erc4337-uint192-key-uint64-sequence-v1"), fee=domain("erc4337-no-paymaster-explicit-max-total-fee-v1")
        try equal(try s(manifest,"accountModelId"),accountModel, field:"manifest.accountModelId");try equal(try s(manifest,"scopeCanonicalizationId"),scopeCanon, field:"manifest.scopeCanonicalizationId");try equal(try s(manifest,"actionCodecId"),codec, field:"manifest.actionCodecId");try equal(try s(manifest,"replayModelId"),replay, field:"manifest.replayModelId");try equal(try s(manifest,"feeModelId"),fee, field:"manifest.feeModelId");try equal(try n(manifest,"postQuantumCapability"),0, field:"manifest.postQuantumCapability")
        guard let suites=manifest["supportedDeviceSignatureSuiteIds"] as? [String], suites == [suite], let proofs=manifest["supportedProofSuiteIds"] as? [String], proofs.isEmpty else { throw failure() }
        let manifestHash = hashDynamic(head:[b(domain("PHIL_ADAPTER_MANIFEST_V1")),b(adapter),b(domain("phil-step6c-local-erc4337-adapter-v1")),u("1"),b(network),b(accountModel),b(scopeCanon),b(codec),b(replay),b(fee),nil,nil,u("0"),try bw(manifest,"implementationHash"),try bw(manifest,"auditStatusHash")], tails:[arrayWords(suites),arrayWords(proofs)])
        try equal(try s(manifest,"manifestHash"),manifestHash, field:"manifest.manifestHash");try equal(try s(root,"adapterManifestHash"),manifestHash, field:"root.adapterManifestHash")

        let registry = try object(root,"signatureRegistry", ["formatVersionHash","registryEpoch","inheritedRegistryEpoch","inheritedRegistryHash","routineDeviceSignatureSuiteId","providerProfileId","wireEncodingId","status","externalNetwork","postQuantum","registryHash"])
        let inherited="0xc8c047f325c09f68c50795a4f261b87ed2b5ca0a3a99e669e632727389b87b79"
        try equal(try s(registry,"formatVersionHash"),domain("PHIL_ROUTINE_SIGNATURE_REGISTRY_V2"), field:"registry.formatVersionHash");try equal(try s(registry,"registryEpoch"),"2", field:"registry.registryEpoch");try equal(try s(registry,"inheritedRegistryEpoch"),"1", field:"registry.inheritedRegistryEpoch");try equal(try s(registry,"inheritedRegistryHash"),inherited, field:"registry.inheritedRegistryHash");try equal(try s(registry,"routineDeviceSignatureSuiteId"),suite, field:"registry.routineDeviceSignatureSuiteId");try equal(try s(registry,"providerProfileId"),provider, field:"registry.providerProfileId");try equal(try s(registry,"wireEncodingId"),wire, field:"registry.wireEncodingId");try equal(try n(registry,"status"),1, field:"registry.status");try requireFalse(registry,["externalNetwork","postQuantum"])
        let registryHash=hash([b(domain("PHIL_ROUTINE_SIGNATURE_REGISTRY_V2")),u("2"),u("1"),b(inherited),b(suite),b(provider),b(wire),u("1"),u("0"),u("0")]);try equal(try s(registry,"registryHash"),registryHash, field:"registry.registryHash");try equal(try s(root,"signatureRegistryHash"),registryHash, field:"root.signatureRegistryHash")

        let enrollment = try object(root,"deviceEnrollment", ["formatVersionHash","deviceId","deviceKeyId","deviceEpoch","generation","signatureRegistryHash","signatureSuiteId","providerProfileId","wireEncodingId","publicKeyX963","publicKeyFingerprint","publicKeyX","publicKeyY","secureEnclaveBacked","userPresenceRequired","status","deviceEnrollmentHash"])
        try equal(try s(enrollment,"formatVersionHash"),domain("PHIL_ROUTINE_DEVICE_ENROLLMENT_V2"), field:"enrollment.formatVersionHash");try equal(try s(enrollment,"deviceId"),record.deviceId, field:"enrollment.deviceId");try equal(try s(enrollment,"deviceKeyId"),record.deviceKeyId, field:"enrollment.deviceKeyId");try equal(try s(enrollment,"deviceEpoch"),"1", field:"enrollment.deviceEpoch");try equal(try s(enrollment,"generation"),String(record.generation), field:"enrollment.generation");try equal(try s(enrollment,"signatureRegistryHash"),registryHash, field:"enrollment.signatureRegistryHash");try equal(try s(enrollment,"signatureSuiteId"),suite, field:"enrollment.signatureSuiteId");try equal(try s(enrollment,"providerProfileId"),provider, field:"enrollment.providerProfileId");try equal(try s(enrollment,"wireEncodingId"),wire, field:"enrollment.wireEncodingId");try equal(try s(enrollment,"publicKeyX963"),record.publicKeyX963, field:"enrollment.publicKeyX963");try equal(try s(enrollment,"publicKeyFingerprint"),record.publicKeyFingerprint, field:"enrollment.publicKeyFingerprint");try equal(try bool(enrollment,"secureEnclaveBacked"),record.secureEnclaveBacked, field:"enrollment.secureEnclaveBacked");try equal(try bool(enrollment,"userPresenceRequired"),record.userPresenceRequired, field:"enrollment.userPresenceRequired");try equal(try n(enrollment,"status"),1, field:"enrollment.status")
        let publicKey=try bytes(record.publicKeyX963,65);guard (try? P256.Signing.PublicKey(x963Representation:publicKey)) != nil else { throw failure() };try equal(try s(enrollment,"publicKeyX"),hex(publicKey.subdata(in:1..<33)), field:"enrollment.publicKeyX");try equal(try s(enrollment,"publicKeyY"),hex(publicKey.subdata(in:33..<65)), field:"enrollment.publicKeyY");try equal(record.publicKeyFingerprint,hex(Data(SHA256.hash(data:publicKey))), field:"deviceEnrollment.publicKeyFingerprint")
        let enrollmentHash=hashDynamic(head:[b(domain("PHIL_ROUTINE_DEVICE_ENROLLMENT_V2")),try bw(enrollment,"deviceId"),try bw(enrollment,"deviceKeyId"),u("1"),try uw(enrollment,"generation"),b(registryHash),b(suite),b(provider),b(wire),nil,b(record.publicKeyFingerprint),b(hex(publicKey.subdata(in:1..<33))),b(hex(publicKey.subdata(in:33..<65))),u(record.secureEnclaveBacked ? "1":"0"),u(record.userPresenceRequired ? "1":"0"),u("1")], tails:[dynamicBytes(publicKey)])
        try equal(try s(enrollment,"deviceEnrollmentHash"),enrollmentHash, field:"enrollment.deviceEnrollmentHash");try equal(try s(root,"deviceEnrollmentHash"),enrollmentHash, field:"root.deviceEnrollmentHash")

        return try verifyRemainder(root, bootstrap:bootstrap, record:record, fingerprint:fingerprint, now:now, env:env, environmentHash:environmentHash, manifest:manifest, manifestHash:manifestHash, registryHash:registryHash, enrollmentHash:enrollmentHash)
    }

    private static func verifyRemainder(_ root:[String:Any], bootstrap:RoutineAuthorizationBootstrap,
        record:RoutineApprovalPublicRecord, fingerprint:String, now:UInt64, env:[String:Any], environmentHash:String,
        manifest:[String:Any], manifestHash:String, registryHash:String, enrollmentHash:String) throws -> Verified {
        let config=try object(root,"accountConfiguration",["formatVersionHash","executionEnvironmentHash","adapterManifestHash","applicationId","principalIdHash","scopeId","scopeInstance","scopeEpoch","recoveryEpoch","validatorEpoch","account","accountRuntimeCodeHash","deviceEnrollmentHash","scopedOwnerCommitment","approvedTarget","approvedTargetRuntimeCodeHash","actionTypeHash","nonceKey","maximumValueWei","maximumTotalFeeWei","accountConfigurationHash"])
        let account=try address(config,"account"), target=try address(config,"approvedTarget"), targetCode=try s(config,"approvedTargetRuntimeCodeHash")
        let principal=hash([b(domain("PHIL_ROUTINE_APPLICATION_PRINCIPAL_V1")),b(application)])
        let scopeInstance=hash([b(domain("PHIL_ROUTINE_SCOPE_INSTANCE_V1")),b(scope),b(application),b(environmentHash),a(account)])
        try equal(try s(config,"formatVersionHash"),domain("PHIL_ROUTINE_ACCOUNT_CONFIGURATION_V1"), field:"config.formatVersionHash");try equal(try s(config,"executionEnvironmentHash"),environmentHash, field:"config.executionEnvironmentHash");try equal(try s(config,"adapterManifestHash"),manifestHash, field:"config.adapterManifestHash");try equal(try s(config,"applicationId"),application, field:"config.applicationId");try equal(try s(config,"principalIdHash"),principal, field:"config.principalIdHash");try equal(try s(config,"scopeId"),scope, field:"config.scopeId");try equal(try s(config,"scopeInstance"),scopeInstance, field:"config.scopeInstance");try ones(config,["scopeEpoch","recoveryEpoch","validatorEpoch"]);try equal(try s(config,"deviceEnrollmentHash"),enrollmentHash, field:"config.deviceEnrollmentHash");try equal(try s(config,"actionTypeHash"),actionType, field:"config.actionTypeHash");try equal(try s(config,"maximumValueWei"),"0", field:"config.maximumValueWei")
        let configurationMaximumFee=try uw(config,"maximumTotalFeeWei")
        let configHash=hash([b(domain("PHIL_ROUTINE_ACCOUNT_CONFIGURATION_V1")),b(environmentHash),b(manifestHash),b(application),b(principal),b(scope),b(scopeInstance),u("1"),u("1"),u("1"),a(account),try bw(config,"accountRuntimeCodeHash"),b(enrollmentHash),try bw(config,"scopedOwnerCommitment"),a(target),b(targetCode),b(actionType),try uw(config,"nonceKey",bits:192),u("0"),configurationMaximumFee])
        try equal(try s(config,"accountConfigurationHash"),configHash, field:"config.accountConfigurationHash");try equal(try s(root,"accountConfigurationHash"),configHash, field:"root.accountConfigurationHash")

        let schema=hash([b(domain("PHIL_ROUTINE_PARAMETER_SCHEMA_V1")),a(target),b(targetCode),bytes4(selector),b(recorded)])
        let capability=hash([b(domain("PHIL_ROUTINE_CAPABILITY_V1")),b(application),b(scopeInstance),a(target),b(targetCode),b(actionType),b(schema)])
        let accountCatalog=hash([a(account)]), targetCatalog=hash([a(target),b(targetCode)])
        let ids=[application,network,accountCatalog,targetCatalog,actionType,schema], bound=[application,environmentHash,accountCatalog,targetCatalog,actionType,schema]
        guard let entries=root["catalogEntries"] as? [[String:Any]], entries.count == 6 else { throw failure() }
        var entryHashes=[String]()
        for i in 0..<6 { try exact(entries[i],["kind","entryId","displayText","displayTextHash","boundValueHash","entryHash"]);let displayHash=domain(labels[i]);let entryHash=hash([b(domain("PHIL_ROUTINE_CATALOG_ENTRY_V1")),u(String(i+1)),b(ids[i]),b(displayHash),b(bound[i])]);try equal(try n(entries[i],"kind"),i+1, field:"entries[i].kind");try equal(try s(entries[i],"entryId"),ids[i], field:"entries[i].entryId");try equal(try s(entries[i],"displayText"),labels[i], field:"entries[i].displayText");try equal(try s(entries[i],"displayTextHash"),displayHash, field:"entries[i].displayTextHash");try equal(try s(entries[i],"boundValueHash"),bound[i], field:"entries[i].boundValueHash");try equal(try s(entries[i],"entryHash"),entryHash, field:"entries[i].entryHash");entryHashes.append(entryHash) }
        let catalogHash=hash([b(domain("PHIL_ROUTINE_CATALOG_V1"))]+entryHashes.map(b));try equal(try s(root,"catalogHash"),catalogHash, field:"root.catalogHash")

        let policy=try object(root,"capabilityPolicy",["formatVersionHash","scopedOwnerCommitment","applicationId","principalIdHash","scopeId","scopeInstance","scopeEpoch","recoveryEpoch","validatorEpoch","capabilityId","capabilityEpoch","policyEpoch","executionEnvironmentHash","adapterManifestHash","accountConfigurationHash","deviceEnrollmentHash","catalogHash","approvedTarget","approvedTargetRuntimeCodeHash","actionTypeHash","maximumValueWei","maximumTotalFeeWei","validAfter","validUntil","active","capabilityPolicyHash"])
        try equal(try s(policy,"formatVersionHash"),domain("PHIL_ROUTINE_CAPABILITY_POLICY_V1"), field:"policy.formatVersionHash");for (key,value) in [("scopedOwnerCommitment",try s(config,"scopedOwnerCommitment")),("applicationId",application),("principalIdHash",principal),("scopeId",scope),("scopeInstance",scopeInstance),("capabilityId",capability),("executionEnvironmentHash",environmentHash),("adapterManifestHash",manifestHash),("accountConfigurationHash",configHash),("deviceEnrollmentHash",enrollmentHash),("catalogHash",catalogHash),("approvedTarget",target),("approvedTargetRuntimeCodeHash",targetCode),("actionTypeHash",actionType),("maximumValueWei","0"),("maximumTotalFeeWei",try s(config,"maximumTotalFeeWei"))] { try equal(try s(policy,key),value, field:"policy." + key) };try ones(policy,["scopeEpoch","recoveryEpoch","validatorEpoch","capabilityEpoch","policyEpoch"]);try equal(try bool(policy,"active"),true, field:"policy.active")
        let policyAfter=try uint64(policy,"validAfter"), policyUntil=try uint64(policy,"validUntil");guard policyUntil == policyAfter+86400 else { throw failure() }
        let policyHash=hash([b(domain("PHIL_ROUTINE_CAPABILITY_POLICY_V1")),try bw(config,"scopedOwnerCommitment"),b(application),b(principal),b(scope),b(scopeInstance),u("1"),u("1"),u("1"),b(capability),u("1"),u("1"),b(environmentHash),b(manifestHash),b(configHash),b(enrollmentHash),b(catalogHash),a(target),b(targetCode),b(actionType),u("0"),try uw(config,"maximumTotalFeeWei"),u(String(policyAfter)),u(String(policyUntil)),u("1")]);try equal(try s(policy,"capabilityPolicyHash"),policyHash, field:"policy.capabilityPolicyHash");try equal(try s(root,"capabilityPolicyHash"),policyHash, field:"root.capabilityPolicyHash")

        let action=try object(root,"action",["formatVersionHash","chainId","account","entryPoint","target","targetCalldataHash","accountCallCommitment","valueWei","nonceKey","nonceSequence","userOpNonce","callGasLimit","verificationGasLimit","preVerificationGas","maxFeePerGas","maxPriorityFeePerGas","maxTotalFeeWei","initCodeHash","paymasterAndDataHash","validAfter","validUntil","actionHash"])
        let calldata=try bytes(try s(root,"targetCalldata"));guard calldata.count==68,hex(calldata.prefix(4))==selector,hex(calldata.subdata(in:4..<36))==recorded, calldata.subdata(in:36..<67)==Data(repeating:0,count:31), [0,1].contains(calldata[67]) else { throw failure() }
        let calldataHash=hex(RecoveryKeccak.keccak256(calldata));let summary=domain(calldata[67]==0 ? "Record disclosed harmless value":"Intentionally revert before recording")
        try equal(try s(action,"formatVersionHash"),actionType, field:"action.formatVersionHash");try equal(try s(action,"chainId"),"31337", field:"action.chainId");try equal(try address(action,"account"),account, field:"action.account");try equal(try address(action,"entryPoint"),try address(env,"entryPoint"), field:"action.entryPoint");try equal(try address(action,"target"),target, field:"action.target");try equal(try s(action,"targetCalldataHash"),calldataHash, field:"action.targetCalldataHash");try equal(try s(action,"valueWei"),"0", field:"action.valueWei");try equal(try s(action,"nonceKey"),try s(config,"nonceKey"), field:"action.nonceKey");try equal(try s(action,"initCodeHash"),zero, field:"action.initCodeHash");try equal(try s(action,"paymasterAndDataHash"),zero, field:"action.paymasterAndDataHash")
        let accountCall=hash([b(actionType),a(target),u("0"),b(calldataHash)]);try equal(try s(action,"accountCallCommitment"),accountCall, field:"action.accountCallCommitment")
        let nonce=try shiftedNonce(key:try s(action,"nonceKey"), sequence:try s(action,"nonceSequence"));try equal(try uw(action,"userOpNonce"),nonce, field:"action.userOpNonce")
        let maximum=try multiply(try uw(action,"callGasLimit"),try uw(action,"verificationGasLimit"),try uw(action,"preVerificationGas"),by:try uw(action,"maxFeePerGas"));try equal(try uw(action,"maxTotalFeeWei"),maximum, field:"action.maxTotalFeeWei");guard compare(try uw(action,"maxPriorityFeePerGas"),try uw(action,"maxFeePerGas")) <= 0 else { throw failure() }
        let actionHash=hash([b(actionType),u("31337"),a(account),a(try address(env,"entryPoint")),a(target),b(calldataHash),b(accountCall),u("0"),try uw(action,"nonceKey",bits:192),try uw(action,"nonceSequence",bits:64),nonce,try uw(action,"callGasLimit",bits:128),try uw(action,"verificationGasLimit",bits:128),try uw(action,"preVerificationGas"),try uw(action,"maxFeePerGas",bits:128),try uw(action,"maxPriorityFeePerGas",bits:128),maximum,b(zero),b(zero),try uw(action,"validAfter",bits:48),try uw(action,"validUntil",bits:48)]);try equal(try s(action,"actionHash"),actionHash, field:"action.actionHash");try equal(try s(root,"actionHash"),actionHash, field:"root.actionHash")
        let issued=try uint64(action,"validAfter"), expires=try uint64(action,"validUntil");guard expires==issued+120,issued>=policyAfter,expires<=policyUntil,expires==bootstrap.expiresAt else { throw failure() }
        try validateDevicePolicyBounds(actionMaximumTotalFeeWei:try s(action,"maxTotalFeeWei"),policyMaximumTotalFeeWei:try s(config,"maximumTotalFeeWei"),issuedAt:issued,expiresAt:expires,deviceNow:now)

        let presentation=try object(root,"humanPresentation",["formatVersionHash","applicationId","applicationNameHash","principalIdHash","scopeId","scopeInstance","scopeEpoch","executionEnvironmentHash","networkLabelHash","account","accountLabelHash","target","targetRuntimeCodeHash","targetLabelHash","actionTypeHash","actionLabelHash","parametersHash","parameterSummaryHash","valueWei","maximumTotalFeeWei","validAfter","validUntil","capabilityId","capabilityEpoch","policyHash","policyEpoch","externalNetwork","productionAuthority","meaningfulAssets","humanPresentationHash"])
        let displayHashes=labels.map(domain);try requireFalse(presentation,["externalNetwork","productionAuthority","meaningfulAssets"])
        let presentationWords=[b(domain("PHIL_ROUTINE_HUMAN_PRESENTATION_V1")),b(application),b(displayHashes[0]),b(principal),b(scope),b(scopeInstance),u("1"),b(environmentHash),b(displayHashes[1]),a(account),b(displayHashes[2]),a(target),b(targetCode),b(displayHashes[3]),b(actionType),b(displayHashes[4]),b(actionHash),b(summary),u("0"),maximum,u(String(issued)),u(String(expires)),b(capability),u("1"),b(policyHash),u("1"),u("0"),u("0"),u("0")]
        let presentationHash=hash(presentationWords);let expectedPresentation:[String:String]=["formatVersionHash":domain("PHIL_ROUTINE_HUMAN_PRESENTATION_V1"),"applicationId":application,"applicationNameHash":displayHashes[0],"principalIdHash":principal,"scopeId":scope,"scopeInstance":scopeInstance,"scopeEpoch":"1","executionEnvironmentHash":environmentHash,"networkLabelHash":displayHashes[1],"account":account,"accountLabelHash":displayHashes[2],"target":target,"targetRuntimeCodeHash":targetCode,"targetLabelHash":displayHashes[3],"actionTypeHash":actionType,"actionLabelHash":displayHashes[4],"parametersHash":actionHash,"parameterSummaryHash":summary,"valueWei":"0","maximumTotalFeeWei":try s(action,"maxTotalFeeWei"),"validAfter":String(issued),"validUntil":String(expires),"capabilityId":capability,"capabilityEpoch":"1","policyHash":policyHash,"policyEpoch":"1","humanPresentationHash":presentationHash]
        for (key,value) in expectedPresentation { try equal(try s(presentation,key),value, field:"presentation." + key) };try equal(try s(root,"humanPresentationHash"),presentationHash, field:"root.humanPresentationHash")

        return try verifyFinal(root,bootstrap:bootstrap,record:record,fingerprint:fingerprint,env:env,environmentHash:environmentHash,manifest:manifest,manifestHash:manifestHash,registryHash:registryHash,enrollmentHash:enrollmentHash,config:config,configHash:configHash,catalogHash:catalogHash,policyHash:policyHash,action:action,actionHash:actionHash,calldataHash:calldataHash,presentationHash:presentationHash,issued:issued,expires:expires,account:account,target:target,principal:principal,scopeInstance:scopeInstance,capability:capability,maximum:maximum,summary:summary)
    }

    private static func verifyFinal(_ root:[String:Any], bootstrap:RoutineAuthorizationBootstrap, record:RoutineApprovalPublicRecord,
        fingerprint:String, env:[String:Any], environmentHash:String, manifest:[String:Any], manifestHash:String,
        registryHash:String,enrollmentHash:String,config:[String:Any],configHash:String,catalogHash:String,policyHash:String,
        action:[String:Any],actionHash:String,calldataHash:String,presentationHash:String,issued:UInt64,expires:UInt64,
        account:String,target:String,principal:String,scopeInstance:String,capability:String,maximum:Data,summary:String) throws -> Verified {
        let accountBinding=hash([b(domain("PHIL_EVM_ACCOUNT_BINDING_V1")),b(manifestHash),b(network),b(try s(manifest,"accountModelId")),u("31337"),a(try address(env,"entryPoint")),a(account)])
        let nonceDomain=hash([b(domain("PHIL_EVM_NONCE_DOMAIN_V1")),b(adapter),b(network),a(try address(env,"entryPoint")),a(account),try uw(action,"nonceKey",bits:192)])
        let intent=hash([b(domain("PHIL_EVM_INTENT_V1")),b(manifestHash),b(actionHash),b(accountBinding),b(nonceDomain)])
        let envelope=try object(root,"authorizationEnvelope",["formatVersionHash","operationClass","scopedOwnerCommitment","scopeId","scopeInstance","scopeEpoch","principalIdHash","capabilityId","capabilityEpoch","networkIdHash","accountBindingHash","adapterId","actionTypeHash","parametersHash","intentDigest","policyHash","nonceDomain","nonce","rootProofNullifier","validAfter","validUntil","valueLimit","feeLimit","deviceEpoch","recoveryEpoch","validatorEpoch","deviceSignatureSuiteId","proofDescriptorHash","humanPresentationHash"])
        try equal(try n(envelope,"operationClass"),1, field:"envelope.operationClass");let envelopeExpected:[String:String]=["formatVersionHash":domain("PHIL_AUTHORIZATION_ENVELOPE_V1"),"scopedOwnerCommitment":try s(config,"scopedOwnerCommitment"),"scopeId":scope,"scopeInstance":scopeInstance,"scopeEpoch":"1","principalIdHash":principal,"capabilityId":capability,"capabilityEpoch":"1","networkIdHash":network,"accountBindingHash":accountBinding,"adapterId":adapter,"actionTypeHash":actionType,"parametersHash":actionHash,"intentDigest":intent,"policyHash":policyHash,"nonceDomain":nonceDomain,"nonce":try s(action,"userOpNonce"),"rootProofNullifier":zero,"validAfter":String(issued),"validUntil":String(expires),"valueLimit":"0","feeLimit":try s(action,"maxTotalFeeWei"),"deviceEpoch":"1","recoveryEpoch":"1","validatorEpoch":"1","deviceSignatureSuiteId":suite,"proofDescriptorHash":zero,"humanPresentationHash":presentationHash]
        for (key,value) in envelopeExpected { try equal(try s(envelope,key),value, field:"envelope." + key) }
        let envelopeDigest=hash([b(domain("PHIL_AUTHORIZATION_ENVELOPE_V1")),u("1"),try bw(config,"scopedOwnerCommitment"),b(scope),b(scopeInstance),u("1"),b(principal),b(capability),u("1"),b(network),b(accountBinding),b(adapter),b(actionType),b(actionHash),b(intent),b(policyHash),b(nonceDomain),try uw(action,"userOpNonce"),u(String(issued)),u(String(expires)),u("0"),maximum,u("1"),u("1"),u("1"),b(suite),b(zero),b(presentationHash)]);try equal(try s(root,"authorizationEnvelopeDigest"),envelopeDigest, field:"root.authorizationEnvelopeDigest")

        let core=try object(root,"authorizationCore",["formatVersionHash","protocolContextHash","sessionId","nonceSeed","issuedAt","expiresAt","executionEnvironmentHash","adapterManifestHash","signatureRegistryHash","deviceEnrollmentHash","accountConfigurationHash","catalogHash","capabilityPolicyHash","actionHash","targetCalldataHash","authorizationEnvelopeDigest","rootProofNullifier","humanPresentationHash","authorizationCoreDigest"])
        try equal(try s(core,"sessionId"),hex(bootstrap.sessionId), field:"core.sessionId");try equal(try s(core,"issuedAt"),String(issued), field:"core.issuedAt");try equal(try s(core,"expiresAt"),String(expires), field:"core.expiresAt")
        let coreExpected:[String:String]=["formatVersionHash":domain("PHIL_ROUTINE_AUTHORIZATION_CORE_V1"),"protocolContextHash":domain("PHIL_ROUTINE_AUTHORIZATION_TRANSPORT_V1"),"executionEnvironmentHash":environmentHash,"adapterManifestHash":manifestHash,"signatureRegistryHash":registryHash,"deviceEnrollmentHash":enrollmentHash,"accountConfigurationHash":configHash,"catalogHash":catalogHash,"capabilityPolicyHash":policyHash,"actionHash":actionHash,"targetCalldataHash":calldataHash,"authorizationEnvelopeDigest":envelopeDigest,"rootProofNullifier":zero,"humanPresentationHash":presentationHash]
        for (key,value) in coreExpected { try equal(try s(core,key),value, field:"core." + key) }
        let coreDigest=hash([b(domain("PHIL_ROUTINE_AUTHORIZATION_CORE_V1")),b(domain("PHIL_ROUTINE_AUTHORIZATION_TRANSPORT_V1")),b(hex(bootstrap.sessionId)),try bw(core,"nonceSeed"),u(String(issued)),u(String(expires)),b(environmentHash),b(manifestHash),b(registryHash),b(enrollmentHash),b(configHash),b(catalogHash),b(policyHash),b(actionHash),b(calldataHash),b(envelopeDigest),b(zero),b(presentationHash)]);try equal(try s(core,"authorizationCoreDigest"),coreDigest, field:"core.authorizationCoreDigest");try equal(try s(root,"authorizationCoreDigest"),coreDigest, field:"root.authorizationCoreDigest")
        let approvalNonce=hash([b(domain("PHIL_ROUTINE_APPROVAL_NONCE_V1")),b(coreDigest),b(hex(bootstrap.sessionId)),try bw(core,"nonceSeed")]);try equal(try s(root,"approvalNonce"),approvalNonce, field:"root.approvalNonce")
        let approval=try object(root,"unsignedDeviceApproval",["deviceId","deviceKeyId","deviceEpoch","approvalNonce","approvedAt","approvalExpiresAt"]);let approvalExpected:[String:String]=["deviceId":record.deviceId,"deviceKeyId":record.deviceKeyId,"deviceEpoch":"1","approvalNonce":approvalNonce,"approvedAt":String(issued),"approvalExpiresAt":String(expires)];for (key,value) in approvalExpected { try equal(try s(approval,key),value, field:"approval." + key) }
        let approvalDigest=hash([b(domain("PHIL_DEVICE_APPROVAL_V1")),b(envelopeDigest),b(record.deviceId),b(record.deviceKeyId),u("1"),b(approvalNonce),u(String(issued)),u(String(expires))]);try equal(try s(root,"deviceApprovalDigest"),approvalDigest, field:"root.deviceApprovalDigest")
        let requestId=hash([b(domain("PHIL_ROUTINE_AUTHORIZATION_REQUEST_V1")),b(coreDigest),b(approvalNonce),b(approvalDigest)]);try equal(try s(root,"requestId"),requestId, field:"root.requestId");try equal(requestId,hex(bootstrap.requestId), field:"requestId")
        let requestBytes=try bytes(requestId,32), signing=Data(SHA256.hash(data:b(domain("PHIL_DEVICE_APPROVAL_SIGNING_PREHASH_V2"))+requestBytes));try equal(try s(root,"platformSigningDigest"),hex(signing), field:"root.platformSigningDigest")
        return Verified(requestId:requestBytes,sessionId:bootstrap.sessionId,expiresAt:expires,signingDigest:signing,deviceId:record.deviceId,deviceKeyId:record.deviceKeyId,presentationHash:presentationHash,approvalDigest:approvalDigest,responseFormatVersionHash:domain("PHIL_ROUTINE_AUTHORIZATION_RESPONSE_V1"),deviceEpoch:"1",presentation:RoutineAuthorizationPresentation(application:labels[0],action:labels[4],network:labels[1],account:account,target:target,parameters:summary==domain("Record disclosed harmless value") ? "Record disclosed harmless value":"Intentionally revert before recording",value:"0 wei",maximumFee:"\(try s(action,"maxTotalFeeWei")) wei",expiresAt:expires,comparisonFingerprint:fingerprint))
    }

    /// Reconstructs the complete Sepolia mint binding graph on iPhone. The
    /// Secure Enclave signs the exact PHIL_DEVICE_APPROVAL_V1 digest returned
    /// here; no supplied derived hash is accepted without reconstruction.
    static func verifySepoliaMint(_ root:[String:Any], bootstrap:RoutineAuthorizationBootstrap,
        record:RoutineApprovalPublicRecord,fingerprint:String,now:UInt64)throws->Verified {
        try exact(root,["formatVersionHash","protocolContextHash","sessionId","authorization","deviceId","deviceKeyId","deviceEpoch","approvalNonce","approvedAt","approvalExpiresAt","deviceApprovalDigest","humanPresentation","humanPresentationHash","requestId","platformSigningDigest"])
        try equal(try s(root,"formatVersionHash"),domain("PHIL_SEPOLIA_MINT_DEVICE_REQUEST_V1"), field:"root.formatVersionHash")
        try equal(try s(root,"protocolContextHash"),domain("PHIL_ROUTINE_AUTHORIZATION_TRANSPORT_V1"), field:"root.protocolContextHash")
        try equal(try s(root,"sessionId"),hex(bootstrap.sessionId), field:"root.sessionId")
        try equal(try s(root,"deviceId"),record.deviceId, field:"root.deviceId");try equal(try s(root,"deviceKeyId"),record.deviceKeyId, field:"root.deviceKeyId")
        let deviceEpoch=try s(root,"deviceEpoch");_ = try decimalWord(deviceEpoch);guard deviceEpoch != "0" else { throw failure() }

        let authorization=try object(root,"authorization",["bindings","authorizationEnvelope","authorizationEnvelopeDigest"])
        let bindings=try object(authorization,"bindings",["chainId","entryPoint","factory","smartAccount","actionGate","mintConsumer","mintRecipient","accountNonce","validAfter","validUntil","maximumTotalFeeWei","parametersHash","accountBindingHash","intentDigest","policyHash","humanPresentationHash","scopeInstance"])
        try equal(try s(bindings,"chainId"),"11155111", field:"bindings.chainId")
        let entryPoint=try address(bindings,"entryPoint"),factory=try address(bindings,"factory")
        let account=try address(bindings,"smartAccount"),gate=try address(bindings,"actionGate")
        let consumer=try address(bindings,"mintConsumer"),recipient=try address(bindings,"mintRecipient")
        try equal(entryPoint,"0x0000000071727de22e5e9d8baf0edac6f37da032", field:"bindings.entryPoint")
        let nonce=try uw(bindings,"accountNonce"),validAfter=try uint64(bindings,"validAfter")
        let validUntil=try uint64(bindings,"validUntil"),fee=try uw(bindings,"maximumTotalFeeWei")
        guard validUntil>validAfter,compare(fee,u("0"))>0 else { throw failure() }
        let scopeId=domain("PHIL_SEPOLIA_MINT_SCOPE_V1"),networkId=domain("ETHEREUM_SEPOLIA_CHAIN_11155111")
        let adapterId=domain("PHIL_ERC4337_V07_SEPOLIA_LOCAL_COMPOSED_MINT_V1")
        let actionType=domain("PHIL_SEPOLIA_ZERO_VALUE_MINT_PASS_V1")
        let suiteId=domain("phil-signature-p256-sha256-prehash-raw-rs-low-s-v2")
        let accountBinding=hash([b(domain("PHIL_SEPOLIA_MINT_ACCOUNT_BINDING_V1")),u("11155111"),a(entryPoint),a(factory),a(account),a(gate)])
        let parameters=hash([b(actionType),a(gate),a(consumer),a(recipient),u("0")])
        let scopeInstance=hash([b(scopeId),a(account),a(consumer),a(recipient)])
        let intent=hash([b(domain("PHIL_SEPOLIA_MINT_INTENT_V1")),b(accountBinding),b(parameters),b(networkId),nonce,u(String(validAfter)),u(String(validUntil))])
        let policy=hash([b(domain("PHIL_SEPOLIA_ZERO_VALUE_MINT_POLICY_V1")),b(accountBinding),b(parameters),u("0"),fee,u(String(validAfter)),u(String(validUntil))])
        let presentationHash=hash([b(domain("PHIL_SEPOLIA_MINT_HUMAN_PRESENTATION_V1")),u("11155111"),a(account),a(gate),a(consumer),a(recipient),fee,u(String(validUntil))])
        for (key,value) in [("parametersHash",parameters),("accountBindingHash",accountBinding),("intentDigest",intent),("policyHash",policy),("humanPresentationHash",presentationHash),("scopeInstance",scopeInstance)] { try equal(try s(bindings,key),value, field:"bindings." + key) }

        let envelope=try object(authorization,"authorizationEnvelope",["formatVersionHash","operationClass","scopedOwnerCommitment","scopeId","scopeInstance","scopeEpoch","principalIdHash","capabilityId","capabilityEpoch","networkIdHash","accountBindingHash","adapterId","actionTypeHash","parametersHash","intentDigest","policyHash","nonceDomain","nonce","rootProofNullifier","validAfter","validUntil","valueLimit","feeLimit","deviceEpoch","recoveryEpoch","validatorEpoch","deviceSignatureSuiteId","proofDescriptorHash","humanPresentationHash"])
        try equal(try n(envelope,"operationClass"),2, field:"envelope.operationClass")
        let scopedOwner=try bw(envelope,"scopedOwnerCommitment"),proofDescriptor=try bw(envelope,"proofDescriptorHash")
        let nullifier=try bw(envelope,"rootProofNullifier");guard nullifier != Data(repeating:0,count:32),proofDescriptor != Data(repeating:0,count:32) else { throw failure() }
        let scopeEpoch=try uw(envelope,"scopeEpoch",bits:64),recoveryEpoch=try uw(envelope,"recoveryEpoch",bits:64),validatorEpoch=try uw(envelope,"validatorEpoch",bits:64)
        let principal=hash([b(domain("PHIL_SEPOLIA_MINT_PRINCIPAL_V1")),a(consumer)])
        let nonceDomain=hash([b(domain("PHIL_SEPOLIA_MINT_ACCOUNT_NONCE_V1")),u("11155111"),a(entryPoint),a(account)])
        let zero="0x"+String(repeating:"00",count:32)
        let expected:[String:String]=["formatVersionHash":domain("PHIL_AUTHORIZATION_ENVELOPE_V1"),"scopeId":scopeId,"scopeInstance":scopeInstance,"principalIdHash":principal,"capabilityId":zero,"capabilityEpoch":"1","networkIdHash":networkId,"accountBindingHash":accountBinding,"adapterId":adapterId,"actionTypeHash":actionType,"parametersHash":parameters,"intentDigest":intent,"policyHash":policy,"nonceDomain":nonceDomain,"nonce":try s(bindings,"accountNonce"),"validAfter":String(validAfter),"validUntil":String(validUntil),"valueLimit":"0","feeLimit":try s(bindings,"maximumTotalFeeWei"),"deviceEpoch":deviceEpoch,"deviceSignatureSuiteId":suiteId,"humanPresentationHash":presentationHash]
        for (key,value) in expected { try equal(try s(envelope,key),value, field:"envelope." + key) }
        guard try s(envelope,"scopeEpoch") != "0",try s(envelope,"recoveryEpoch") != "0",try s(envelope,"validatorEpoch") != "0" else { throw failure() }
        let envelopeDigest=hash([b(domain("PHIL_AUTHORIZATION_ENVELOPE_V1")),u("2"),scopedOwner,b(scopeId),b(scopeInstance),scopeEpoch,b(principal),b(zero),u("1"),b(networkId),b(accountBinding),b(adapterId),b(actionType),b(parameters),b(intent),b(policy),b(nonceDomain),nonce,u(String(validAfter)),u(String(validUntil)),u("0"),fee,try uw(envelope,"deviceEpoch",bits:64),recoveryEpoch,validatorEpoch,b(suiteId),proofDescriptor,b(presentationHash)])
        try equal(try s(authorization,"authorizationEnvelopeDigest"),envelopeDigest, field:"authorization.authorizationEnvelopeDigest")

        let review=try object(root,"humanPresentation",["network","smartAccount","mintRecipient","contract","action","value","maximumFeeWei","expiresAt","consequence","verificationBoundary"])
        let reviewExpected:[String:String]=["network":"Ethereum Sepolia (chain 11155111)","smartAccount":account,"mintRecipient":recipient,"contract":consumer,"action":"Mint one harmless, non-transferable Phil test pass","value":"0 ETH","maximumFeeWei":try s(bindings,"maximumTotalFeeWei"),"expiresAt":String(validUntil),"consequence":"Ethereum records a public test-pass event; no token, asset, or ETH is transferred.","verificationBoundary":"Noir proof and iPhone approval are verified locally; Ethereum enforces the restricted account signature and ActionGate."]
        for (key,value) in reviewExpected { try equal(try s(review,key),value, field:"review." + key) };try equal(try s(root,"humanPresentationHash"),presentationHash, field:"root.humanPresentationHash")

        let approvedAt=try uint64(root,"approvedAt"),approvalExpires=try uint64(root,"approvalExpiresAt")
        guard approvedAt<=now,now<=approvalExpires,approvalExpires<=validUntil,approvalExpires==bootstrap.expiresAt else { throw failure() }
        let approvalNonce=try bw(root,"approvalNonce")
        let approvalDigest=hash([b(domain("PHIL_DEVICE_APPROVAL_V1")),b(envelopeDigest),b(record.deviceId),b(record.deviceKeyId),try uw(root,"deviceEpoch",bits:64),approvalNonce,u(String(approvedAt)),u(String(approvalExpires))])
        try equal(try s(root,"deviceApprovalDigest"),approvalDigest, field:"root.deviceApprovalDigest");try equal(try s(root,"platformSigningDigest"),approvalDigest, field:"root.platformSigningDigest")
        let requestId=hash([b(domain("PHIL_SEPOLIA_MINT_DEVICE_REQUEST_ID_V1")),b(hex(bootstrap.sessionId)),b(envelopeDigest),approvalNonce,b(approvalDigest)])
        try equal(try s(root,"requestId"),requestId, field:"root.requestId");try equal(requestId,hex(bootstrap.requestId), field:"requestId")
        let requestBytes=try bytes(requestId,32),signing=try bytes(approvalDigest,32)
        return Verified(requestId:requestBytes,sessionId:bootstrap.sessionId,expiresAt:approvalExpires,signingDigest:signing,deviceId:record.deviceId,deviceKeyId:record.deviceKeyId,presentationHash:presentationHash,approvalDigest:approvalDigest,responseFormatVersionHash:domain("PHIL_SEPOLIA_MINT_DEVICE_RESPONSE_V1"),deviceEpoch:deviceEpoch,presentation:RoutineAuthorizationPresentation(application:"PhilCore",action:"Mint one harmless, non-transferable Phil test pass",network:"Ethereum Sepolia (chain 11155111)",account:account,target:consumer,parameters:"Recipient \(recipient); public test-pass event only",value:"0 ETH",maximumFee:"\(try s(bindings,"maximumTotalFeeWei")) wei",expiresAt:approvalExpires,comparisonFingerprint:fingerprint))
    }

    private static func failure() -> RoutineAuthorizationFailure { .malformedRequest }
    static func validateDevicePolicyBounds(actionMaximumTotalFeeWei:String,policyMaximumTotalFeeWei:String,issuedAt:UInt64,expiresAt:UInt64,deviceNow:UInt64)throws {
        let actionFee=try decimalWord(actionMaximumTotalFeeWei),policyFee=try decimalWord(policyMaximumTotalFeeWei)
        guard compare(actionFee,policyFee)<=0,deviceNow>=issuedAt-min(issuedAt,5),deviceNow<=expiresAt else { throw failure() }
    }
    private static func exact(_ value:[String:Any],_ keys:[String]) throws { guard Set(value.keys)==Set(keys) else { throw failure() } }
    private static func object(_ parent:[String:Any],_ key:String,_ keys:[String]) throws->[String:Any] { guard let value=parent[key] as? [String:Any] else { throw failure() };try exact(value,keys);return value }
    private static func s(_ parent:[String:Any],_ key:String) throws->String { guard let value=parent[key] as? String else { throw failure() };return value }
    private static func n(_ parent:[String:Any],_ key:String) throws->Int { guard let value=parent[key] as? Int else { throw failure() };return value }
    private static func bool(_ parent:[String:Any],_ key:String) throws->Bool { guard let value=parent[key] as? Bool else { throw failure() };return value }
    private static func equal<T:Equatable>(_ actual:T,_ expected:T,field:String) throws { guard actual==expected else { throw RoutineBindingMismatch(field:field) } }
    private static func requireFalse(_ value:[String:Any],_ keys:[String]) throws { for key in keys { try equal(try bool(value,key),false, field:"value." + key) } }
    private static func ones(_ value:[String:Any],_ keys:[String]) throws { for key in keys { try equal(try s(value,key),"1", field:"value." + key) } }
    private static func address(_ parent:[String:Any],_ key:String) throws->String { let value=try s(parent,key);guard value==value.lowercased(),(try? bytes(value,20)) != nil,value != "0x"+String(repeating:"00",count:20) else { throw failure() };return value }
    private static func uint64(_ parent:[String:Any],_ key:String) throws->UInt64 { let text=try s(parent,key);guard canonical(text),let value=UInt64(text) else { throw failure() };return value }
    private static func canonical(_ text:String)->Bool { !text.isEmpty && text.utf8.allSatisfy({ (48...57).contains($0) }) && (text=="0" || text.first != "0") }
    private static func domain(_ label:String)->String { hex(RecoveryKeccak.keccak256(Data(label.utf8))) }
    private static func hex<T:DataProtocol>(_ data:T)->String { "0x"+data.map{String(format:"%02x",$0)}.joined() }
    private static func bytes(_ hex:String,_ length:Int?=nil) throws->Data { guard hex.hasPrefix("0x"),hex==hex.lowercased(),hex.count%2==0 else { throw failure() };var out=Data(),i=hex.index(hex.startIndex,offsetBy:2);while i<hex.endIndex { let e=hex.index(i,offsetBy:2);guard let v=UInt8(hex[i..<e],radix:16) else { throw failure() };out.append(v);i=e };if let length { guard out.count==length else { throw failure() } };return out }
    private static func b(_ value:String)->Data { (try? bytes(value,32)) ?? Data() }
    private static func bw(_ parent:[String:Any],_ key:String) throws->Data { try bytes(try s(parent,key),32) }
    private static func a(_ value:String)->Data { Data(repeating:0,count:12)+((try? bytes(value,20)) ?? Data()) }
    private static func bytes4(_ value:String)->Data { ((try? bytes(value,4)) ?? Data())+Data(repeating:0,count:28) }
    private static func u(_ text:String)->Data { (try? decimalWord(text)) ?? Data() }
    private static func uw(_ parent:[String:Any],_ key:String,bits:Int=256) throws->Data { let result=try decimalWord(try s(parent,key));guard result.prefix((256-bits)/8).allSatisfy({$0==0}) else { throw failure() };return result }
    private static func decimalWord(_ text:String)throws->Data { guard canonical(text) else { throw failure() };var out=[UInt8](repeating:0,count:32);for c in text { var carry=Int(String(c))!;for i in stride(from:31,through:0,by:-1){let x=Int(out[i])*10+carry;out[i]=UInt8(x&255);carry=x>>8};guard carry==0 else { throw failure() } };return Data(out) }
    private static func hash(_ words:[Data])->String { guard words.allSatisfy({$0.count==32}) else { return "" };return hex(RecoveryKeccak.keccak256(words.reduce(into:Data()){$0.append($1)})) }
    private static func dynamicBytes(_ data:Data)->Data { u(String(data.count))+data+Data(repeating:0,count:(32-data.count%32)%32) }
    private static func arrayWords(_ values:[String])->Data { u(String(values.count))+values.map(b).reduce(into:Data()){$0.append($1)} }
    private static func hashDynamic(head:[Data?],tails:[Data])->String { var offset=head.count*32,tailIndex=0,varHead=Data(),body=Data();for item in head { if let item { varHead.append(item) } else { varHead.append(u(String(offset)));offset += tails[tailIndex].count;body.append(tails[tailIndex]);tailIndex += 1 } };return hex(RecoveryKeccak.keccak256(varHead+body)) }
    // Foundation Data slices retain their original indices. Build a fresh word,
    // preserving exactly uint192 key || uint64 sequence, without shifted indices.
    static func shiftedNonce(key:String,sequence:String)throws->Data {
        let keyWord = try decimalWord(key), sequenceWord = try decimalWord(sequence)
        guard keyWord.prefix(8).allSatisfy({ $0 == 0 }),
              sequenceWord.prefix(24).allSatisfy({ $0 == 0 }) else { throw failure() }
        return Data(keyWord.suffix(24)) + Data(sequenceWord.suffix(8))
    }
    private static func multiply(_ a:Data,_ b:Data,_ c:Data,by d:Data)throws->Data { let sum=try add(try add(a,b),c);return try mul(sum,d) }
    private static func add(_ a:Data,_ b:Data)throws->Data { var out=[UInt8](repeating:0,count:32),carry=0;for i in stride(from:31,through:0,by:-1){let x=Int(a[i])+Int(b[i])+carry;out[i]=UInt8(x&255);carry=x>>8};guard carry==0 else { throw failure() };return Data(out) }
    private static func mul(_ a:Data,_ b:Data)throws->Data { let x=a.reversed().map(Int.init),y=b.reversed().map(Int.init);var z=[Int](repeating:0,count:64);for i in 0..<32 { for j in 0..<32 { z[i+j]+=x[i]*y[j] } };for i in 0..<63 { z[i+1]+=z[i]>>8;z[i]&=255 };guard z[32...].allSatisfy({$0==0}) else { throw failure() };return Data(z[0..<32].reversed().map(UInt8.init)) }
    private static func compare(_ a:Data,_ b:Data)->Int { a.lexicographicallyPrecedes(b) ? -1 : b.lexicographicallyPrecedes(a) ? 1 : 0 }
}
