[package]
name = "phil_starknet_spike"
version = "0.1.0"
edition = "2024_07"
license = "MIT"

[dependencies]
starknet = "2.15.0"

[dev-dependencies]
cairo_test = "2.15.0"

[[target.starknet-contract]]
casm = true
