#!/usr/bin/env node
"use strict";
const fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");
const {directorySha256}=require("./release-artifact-lineage.cjs");
const {verifyNotices}=require("./distribution-notices.cjs");
const {verifyCoverage}=require("./native-notice-coverage.cjs");
const hash=(b)=>crypto.createHash("sha256").update(b).digest("hex");
function inventoryFiles(root){const result=[];function walk(dir){for(const name of fs.readdirSync(dir).sort()){const file=path.join(dir,name),stat=fs.lstatSync(file),relative=path.relative(root,file).split(path.sep).join("/");if(stat.isSymbolicLink())result.push({path:relative,type:"symlink",target:fs.readlinkSync(file)});else if(stat.isDirectory())walk(file);else if(stat.isFile())result.push({path:relative,type:"file",bytes:stat.size,mode:stat.mode&0o777,sha256:hash(fs.readFileSync(file))});else throw Error(`unsupported_bundle_entry:${relative}`);}}walk(root);return result;}
function createSbom(app,source={}){
 const payload=path.join(app,"Contents/Resources/app"),selection=JSON.parse(fs.readFileSync(path.join(payload,"config/release/runtime-package-inventory.json")));const notices=verifyNotices(payload);const files=inventoryFiles(app);
 const packages=files.filter(f=>/\/node_modules\/(?:@[^/]+\/)?[^/]+\/package.json$/.test(f.path)).map(f=>{const p=JSON.parse(fs.readFileSync(path.join(app,f.path)));return{path:f.path.replace("Contents/Resources/app/","").replace(/\/package.json$/,""),name:p.name,version:p.version,declaredLicense:p.license||null,packageJsonSha256:f.sha256};}).sort((a,b)=>a.path.localeCompare(b.path));
 if(JSON.stringify(packages.map(p=>[p.path,p.name,p.version]))!==JSON.stringify(selection.packages.map(p=>[p.path,p.name,p.version])))throw Error("sbom_runtime_inventory_mismatch");
 for(const p of packages)if(!notices.some(n=>n.packagePath===p.path))throw Error(`sbom_package_notice_missing:${p.path}`);
 const native=files.filter(f=>f.type==='file').filter(f=>{const fd=fs.openSync(path.join(app,f.path),'r'),b=Buffer.alloc(4);try{if(fs.readSync(fd,b,0,4,0)!==4)return false;return[0xfeedface,0xcefaedfe,0xfeedfacf,0xcffaedfe,0xcafebabe,0xbebafeca,0xcafebabf,0xbfbafeca].includes(b.readUInt32BE());}finally{fs.closeSync(fd);}}).map(f=>({path:f.path,sha256:f.sha256,bytes:f.bytes}));
 return{schemaVersion:2,format:"philcore-shipped-artifact-sbom-v2",generatedAt:new Date().toISOString(),source,appBundleSha256:directorySha256(app),packageLockSha256:hash(fs.readFileSync(path.join(payload,"package-lock.json"))),packages:packages.map(p=>({...p,...selection.packages.find(s=>s.path===p.path)})),hardhatModification:selection.hardhatModification,nativeComponents:native,nativeNoticeCoverage:verifyCoverage(app),notices,files,scope:"Exact final app, including Electron/Chromium/Node framework and every native file; lockfile dev flags are not exposure classifications",publicNetworkMutation:false};
}
function verifySbom(app,sbom){if(sbom.format!=="philcore-shipped-artifact-sbom-v2"||directorySha256(app)!==sbom.appBundleSha256)throw Error("sbom_artifact_hash_mismatch");const actual=createSbom(app,sbom.source);for(const key of["packages","nativeComponents","nativeNoticeCoverage","notices","files"])if(JSON.stringify(actual[key])!==JSON.stringify(sbom[key]))throw Error(`sbom_${key}_mismatch`);return true;}
if(require.main===module){const release=require("./release-utils.cjs");const app=process.env.PHILCORE_DESKTOP_TEST_APP_PATH||release.appBundlePath;const output=process.argv[2]||path.join(release.releaseRoot,"philcore-desktop-sbom.json");const {sourceIdentity}=require("./release-artifact-lineage.cjs");const sbom=createSbom(app,sourceIdentity());fs.writeFileSync(output,JSON.stringify(sbom,null,2)+"\n");verifySbom(app,sbom);console.log(JSON.stringify({status:"passed",output,appBundleSha256:sbom.appBundleSha256,packages:sbom.packages.length,nativeComponents:sbom.nativeComponents.length,files:sbom.files.length}));}
module.exports={inventoryFiles,createSbom,verifySbom};
