[package]
name = "phil_cairo_air_adapter_spike"
version = "0.1.0"
edition = "2024_07"
license = "MIT"

[lib]

[dependencies]
stwo_verifier_core = { path = "../vendor/stwo_cairo_verifier/crates/verifier_core" }
stwo_constraint_framework = { path = "../vendor/stwo_cairo_verifier/crates/constraint_framework" }
cairo_execute = "2.15.0"

[dev-dependencies]
cairo_test = "2.15.0"

[cairo]
enable-gas = false

[[target.executable]]
